[Show site average usage in different time period]
header=Site/Time period(hours)|Count of requests|Avg CPU %|Avg Mem %|Avg IO(KB/s);
ssql=select tt1.r2, IFNULL(tt2.m1,' '), IFNULL(tt2.m2, ' '), IFNULL(tt2.m5, ' '), IFNULL(tt2.m6, ' ') from (select 1 as r0, :FORHOST: as r1,:FORHOST: as r2 from :TBL: where :FILTER: and :PERIOD: group by :FORHOST: union select t2.fld1 as r1, t1.:FORHOST: as r2, t2.fld as r0 from :TBL: as t1, (select 2 as fld1, '0-8' as fld union select 3 as fld1, '8-12' as fld union select 4 as fld1, '12-18' as fld union select 5 as fld1, '18-24' as fld) as t2 where  :FILTER: and :PERIOD: order by 2,1) as tt1 left join (select count(*) as m1, sum(:CPUUSAGE:)/count(*) as m2, sum(:MEMUSAGEINPRCT:)/count(*) as m5, sum(:BYTESREAD: + :BYTESWRITE:)/count(*) as m6, :FORHOST: as m3, case when strftime("%H", :DATEADD:)+0 between 0 and 8 then '0-8' when strftime("%H", :DATEADD:)+0 between 9 and 12 then '8-12' when strftime("%H", :DATEADD:)+0 between 13 and 18 then '12-18' else '18-24' end as m4 from :TBL: where :FILTER: and :PERIOD: group by m3,m4) as tt2 on tt1.r1 = tt2.m3 and tt1.r2 = tt2.m4 order by tt1.r1, tt1.r0;
msql=select tt1.r2, IFNULL(tt2.m1,' '), IFNULL(tt2.m2, ' '), IFNULL(tt2.m5, ' '), IFNULL(tt2.m6, ' ') from (select 1 as r0, :FORHOST: as r1,:FORHOST: as r2 from :TBL: where :FILTER: and :PERIOD: group by :FORHOST: union select t2.fld1 as r1, t1.:FORHOST: as r2, t2.fld as r0 from :TBL: as t1, (select 2 as fld1, '0-8' as fld union select 3 as fld1, '8-12' as fld union select 4 as fld1, '12-18' as fld union select 5 as fld1, '18-24' as fld) as t2 where  :FILTER: and :PERIOD: order by 2,1) as tt1 left join (select count(*) as m1, sum(:CPUUSAGE:)/count(*) as m2, sum(:MEMUSAGEINPRCT:)/count(*) as m5, sum(:BYTESREAD: + :BYTESWRITE:)/count(*) as m6, :FORHOST: as m3, case when HOUR(:DATEADD:) between 0 and 8 then '0-8' when HOUR(:DATEADD:) between 9 and 12 then '8-12' when HOUR(:DATEADD:) between 13 and 18 then '12-18' else '18-24' end as m4 from :TBL: where :FILTER: and :PERIOD: group by m3,m4) as tt2 on tt1.r1 = tt2.m3 and tt1.r2 = tt2.m4 order by tt1.r1, tt1.r0;
psql=select tt1.r2, coalesce(CAST(tt2.m1 as text),' '), coalesce(CAST(tt2.m2 as text), ' '), coalesce(CAST(tt2.m5 as text), ' '), coalesce(CAST(tt2.m6 as text), ' ') from (select 1 as r0, :FORHOST: as r1,:FORHOST: as r2 from :TBL: where :FILTER: and :PERIOD: group by :FORHOST: union select t2.fld1 as r1, t1.:FORHOST: as r2, t2.fld as r0 from :TBL: as t1, (select 2 as fld1, '0-8' as fld union select 3 as fld1, '8-12' as fld union select 4 as fld1, '12-18' as fld union select 5 as fld1, '18-24' as fld) as t2 where  :FILTER: and :PERIOD: order by 2,1) as tt1 left join (select count(*) as m1, sum(:CPUUSAGE:)/count(*) as m2, sum(:MEMUSAGEINPRCT:)/count(*) as m5, sum(:BYTESREAD: + :BYTESWRITE:)/count(*) as m6, :FORHOST: as m3, case when extract(hour from :DATEADD:) between 0 and 8 then '0-8' when extract(hour from :DATEADD:) between 9 and 12 then '8-12' when extract(hour from :DATEADD:) between 13 and 18 then '12-18' else '18-24' end as m4 from :TBL: where :FILTER: and :PERIOD: group by m3,m4) as tt2 on tt1.r1 = tt2.m3 and tt1.r2 = tt2.m4 order by tt1.r1, tt1.r0;

[Show most popular script by site]
header=Site| Popular script|Requests of script|Avg CPU|Avg Mem|Avg IO;
ssql=select tt1.:FORHOST:, tt1.:CALLEDSCRIPT:, tt1.t1, tt1.t2, tt1.t3, tt1.t4 from (select count(*) as t1, sum(:CPUUSAGE:)/count(*) as t2, sum(:MEMUSAGEINPRCT:)/count(*) as t3, sum(:BYTESREAD:+:BYTESWRITE:)/count(*) as t4,  :CALLEDSCRIPT:, :FORHOST: from :TBL: where :FILTER: and :PERIOD: group by :CALLEDSCRIPT:,:FORHOST:) as tt1 join (select max(t1.t1) as mx, t1.:FORHOST: as :FORHOST: from (select count(*) as t1, :CALLEDSCRIPT:, :FORHOST: from :TBL: where :FILTER: and :PERIOD: group by :CALLEDSCRIPT:,:FORHOST:) as t1 group by :FORHOST:) as tt2 on tt1.t1 = tt2.mx and tt1.:FORHOST: = tt2.:FORHOST: order by tt2.:FORHOST:;
msql=select tt1.:FORHOST:, tt1.:CALLEDSCRIPT:, tt1.t1, tt1.t2, tt1.t3, tt1.t4 from (select count(*) as t1, sum(:CPUUSAGE:)/count(*) as t2, sum(:MEMUSAGEINPRCT:)/count(*) as t3, sum(:BYTESREAD:+:BYTESWRITE:)/count(*) as t4,  :CALLEDSCRIPT:, :FORHOST: from :TBL: where :FILTER: and :PERIOD: group by :CALLEDSCRIPT:,:FORHOST:) as tt1 join (select max(t1.t1) as mx, t1.:FORHOST: from (select count(*) as t1, :CALLEDSCRIPT:, :FORHOST: from :TBL: where :FILTER: and :PERIOD: group by :CALLEDSCRIPT:,:FORHOST:) as t1 group by :FORHOST:) as tt2 on tt1.t1 = tt2.mx and tt1.:FORHOST: = tt2.:FORHOST: order by tt2.:FORHOST:;
psql=select tt1.:FORHOST:, tt1.:CALLEDSCRIPT:, tt1.t1, tt1.t2, tt1.t3, tt1.t4 from (select count(*) as t1, sum(:CPUUSAGE:)/count(*) as t2, sum(:MEMUSAGEINPRCT:)/count(*) as t3, sum(:BYTESREAD:+:BYTESWRITE:)/count(*) as t4,  :CALLEDSCRIPT:, :FORHOST: from :TBL: where :FILTER: and :PERIOD: group by :CALLEDSCRIPT:,:FORHOST:) as tt1 join (select max(t1.t1) as mx, t1.:FORHOST: from (select count(*) as t1, :CALLEDSCRIPT:, :FORHOST: from :TBL: where :FILTER: and :PERIOD: group by :CALLEDSCRIPT:,:FORHOST:) as t1 group by :FORHOST:) as tt2 on tt1.t1 = tt2.mx and tt1.:FORHOST: = tt2.:FORHOST: order by tt2.:FORHOST:;

[Show CPU load range by site]
header=Site/CPU Load|Count requests;
ssql=select tt1.r2, IFNULL(tt2.m1,0) from (select 1 as r0, :FORHOST: as r1,:FORHOST: as r2 from :TBL: where :FILTER: and :PERIOD: group by :FORHOST: union select t2.fld1 as r1, t1.:FORHOST: as r2, t2.fld as r0 from :TBL: as t1, (select 2 as fld1, '100%' as fld union select 3 as fld1, '75%' as fld union select 4 as fld1, '50%' as fld union select 5 as fld1, '25%' as fld union select 6 as fld1, '0%' as fld) as t2 where :FILTER: and :PERIOD: order by 2,1) as tt1 left join (select count(*) as m1, :FORHOST: as m2, case when :CPUUSAGE: <= 1 then '0%' when :CPUUSAGE: > 1 and :CPUUSAGE: <= 25 then '25%' when :CPUUSAGE: > 25 and :CPUUSAGE: <= 50 then '50%' when :CPUUSAGE: > 50 and :CPUUSAGE: <= 75 then '75%' else '100%' end as m4 from :TBL: where :FILTER: and :PERIOD:  group by m2,m4) as tt2 on tt1.r1 = tt2.m2 and tt1.r2 = tt2.m4 order by tt1.r1, tt1.r0;
msql=select tt1.r2, IFNULL(tt2.m1,0) from (select 1 as r0, :FORHOST: as r1,:FORHOST: as r2 from :TBL: where :FILTER: and :PERIOD: group by :FORHOST: union select t2.fld1 as r1, t1.:FORHOST: as r2, t2.fld as r0 from :TBL: as t1, (select 2 as fld1, '100%' as fld union select 3 as fld1, '75%' as fld union select 4 as fld1, '50%' as fld union select 5 as fld1, '25%' as fld union select 6 as fld1, '0%' as fld) as t2 where :FILTER: and :PERIOD: order by 2,1) as tt1 left join (select count(*) as m1, :FORHOST: as m2, case when :CPUUSAGE: <= 1 then '0%' when :CPUUSAGE: > 1 and :CPUUSAGE: <= 25 then '25%' when :CPUUSAGE: > 25 and :CPUUSAGE: <= 50 then '50%' when :CPUUSAGE: > 50 and :CPUUSAGE: <= 75 then '75%' else '100%' end as m4 from :TBL: where :FILTER: and :PERIOD:  group by m2,m4) as tt2 on tt1.r1 = tt2.m2 and tt1.r2 = tt2.m4 order by tt1.r1, tt1.r0;
psql=select tt1.r2, coalesce(tt2.m1,0) from (select 1 as r0, :FORHOST: as r1,:FORHOST: as r2 from :TBL: where :FILTER: and :PERIOD: group by :FORHOST: union select t2.fld1 as r1, t1.:FORHOST: as r2, t2.fld as r0 from :TBL: as t1, (select 2 as fld1, '100%' as fld union select 3 as fld1, '75%' as fld union select 4 as fld1, '50%' as fld union select 5 as fld1, '25%' as fld union select 6 as fld1, '0%' as fld) as t2 where :FILTER: and :PERIOD: order by 2,1) as tt1 left join (select count(*) as m1, :FORHOST: as m2, case when :CPUUSAGE: <= 1 then '0%' when :CPUUSAGE: > 1 and :CPUUSAGE: <= 25 then '25%' when :CPUUSAGE: > 25 and :CPUUSAGE: <= 50 then '50%' when :CPUUSAGE: > 50 and :CPUUSAGE: <= 75 then '75%' else '100%' end as m4 from :TBL: where :FILTER: and :PERIOD:  group by m2,m4) as tt2 on tt1.r1 = tt2.m2 and tt1.r2 = tt2.m4 order by tt1.r1, tt1.r0;

[Show Memory Usage range by site]
header=Site/Memory Usage|Count requests;
ssql=select tt1.r2, IFNULL(tt2.m1,0) from (select 1 as r0, :FORHOST: as r1,:FORHOST: as r2 from :TBL: where :FILTER: and :PERIOD: group by :FORHOST: union select t2.fld1 as r1, t1.:FORHOST: as r2, t2.fld as r0 from :TBL: as t1, (select 2 as fld1, '100%' as fld union select 3 as fld1, '75%' as fld union select 4 as fld1, '50%' as fld union select 5 as fld1, '25%' as fld union select 6 as fld1, '0%' as fld) as t2 where :FILTER: and :PERIOD: order by 2,1) as tt1 left join (select count(*) as m1, :FORHOST: as m2, case when :MEMUSAGEINPRCT: <= 1 then '0%' when :MEMUSAGEINPRCT: > 1 and :MEMUSAGEINPRCT: <= 25 then '25%' when :MEMUSAGEINPRCT: > 25 and :MEMUSAGEINPRCT: <= 50 then '50%' when :MEMUSAGEINPRCT: > 50 and :MEMUSAGEINPRCT: <= 75 then '75%' else '100%' end as m4 from :TBL: where :FILTER: and :PERIOD:  group by m2,m4) as tt2 on tt1.r1 = tt2.m2 and tt1.r2 = tt2.m4 order by tt1.r1, tt1.r0;
msql=select tt1.r2, IFNULL(tt2.m1,0) from (select 1 as r0, :FORHOST: as r1,:FORHOST: as r2 from :TBL: where :FILTER: and :PERIOD: group by :FORHOST: union select t2.fld1 as r1, t1.:FORHOST: as r2, t2.fld as r0 from :TBL: as t1, (select 2 as fld1, '100%' as fld union select 3 as fld1, '75%' as fld union select 4 as fld1, '50%' as fld union select 5 as fld1, '25%' as fld union select 6 as fld1, '0%' as fld) as t2 where :FILTER: and :PERIOD: order by 2,1) as tt1 left join (select count(*) as m1, :FORHOST: as m2, case when :MEMUSAGEINPRCT: <= 1 then '0%' when :MEMUSAGEINPRCT: > 1 and :MEMUSAGEINPRCT: <= 25 then '25%' when :MEMUSAGEINPRCT: > 25 and :MEMUSAGEINPRCT: <= 50 then '50%' when :MEMUSAGEINPRCT: > 50 and :MEMUSAGEINPRCT: <= 75 then '75%' else '100%' end as m4 from :TBL: where :FILTER: and :PERIOD:  group by m2,m4) as tt2 on tt1.r1 = tt2.m2 and tt1.r2 = tt2.m4 order by tt1.r1, tt1.r0;
psql=select tt1.r2, coalesce(tt2.m1,0) from (select 1 as r0, :FORHOST: as r1,:FORHOST: as r2 from :TBL: where :FILTER: and :PERIOD: group by :FORHOST: union select t2.fld1 as r1, t1.:FORHOST: as r2, t2.fld as r0 from :TBL: as t1, (select 2 as fld1, '100%' as fld union select 3 as fld1, '75%' as fld union select 4 as fld1, '50%' as fld union select 5 as fld1, '25%' as fld union select 6 as fld1, '0%' as fld) as t2 where :FILTER: and :PERIOD: order by 2,1) as tt1 left join (select count(*) as m1, :FORHOST: as m2, case when :MEMUSAGEINPRCT: <= 1 then '0%' when :MEMUSAGEINPRCT: > 1 and :MEMUSAGEINPRCT: <= 25 then '25%' when :MEMUSAGEINPRCT: > 25 and :MEMUSAGEINPRCT: <= 50 then '50%' when :MEMUSAGEINPRCT: > 50 and :MEMUSAGEINPRCT: <= 75 then '75%' else '100%' end as m4 from :TBL: where :FILTER: and :PERIOD:  group by m2,m4) as tt2 on tt1.r1 = tt2.m2 and tt1.r2 = tt2.m4 order by tt1.r1, tt1.r0;

[Show Max CPU load in different time periods by site]
header=Site/Time period(hours)|Max CPU usage %;
ssql=select tt1.r2, IFNULL(tt2.m2, 0.0) from (select 1 as r0, :FORHOST: as r1,:FORHOST: as r2 from :TBL: where :FILTER: and :PERIOD: group by :FORHOST: union select t2.fld1 as r1, t1.:FORHOST: as r2, t2.fld as r0 from :TBL: as t1, (select 2 as fld1, '0-8' as fld union select 3 as fld1, '8-12' as fld union select 4 as fld1, '12-18' as fld union select 5 as fld1, '18-24' as fld) as t2 where :FILTER: and :PERIOD: order by 2,1) as tt1 left join (select max(:CPUUSAGE:) as m2, :FORHOST: as m3, case when strftime("%H", :DATEADD:)+0 between 0 and 8 then '0-8' when strftime("%H", :DATEADD:)+0 between 9 and 12 then '8-12' when strftime("%H", :DATEADD:)+0 between 13 and 18 then '12-18' else '18-24' end as m4 from :TBL: where :FILTER: and :PERIOD: group by m3,m4) as tt2 on tt1.r1 = tt2.m3 and tt1.r2 = tt2.m4 order by tt1.r1, tt1.r0;
msql=select tt1.r2, IFNULL(tt2.m2, 0.0) from (select 1 as r0, :FORHOST: as r1,:FORHOST: as r2 from :TBL: where :FILTER: and :PERIOD: group by :FORHOST: union select t2.fld1 as r1, t1.:FORHOST: as r2, t2.fld as r0 from :TBL: as t1, (select 2 as fld1, '0-8' as fld union select 3 as fld1, '8-12' as fld union select 4 as fld1, '12-18' as fld union select 5 as fld1, '18-24' as fld) as t2 where :FILTER: and :PERIOD: order by 2,1) as tt1 left join (select max(:CPUUSAGE:) as m2, :FORHOST: as m3, case when HOUR(:DATEADD:) between 0 and 8 then '0-8' when HOUR(:DATEADD:) between 9 and 12 then '8-12' when HOUR(:DATEADD:) between 13 and 18 then '12-18' else '18-24' end as m4 from :TBL: where :FILTER: and :PERIOD: group by m3,m4) as tt2 on tt1.r1 = tt2.m3 and tt1.r2 = tt2.m4 order by tt1.r1, tt1.r0;
psql=select tt1.r2, coalesce(tt2.m2, 0.0) from (select 1 as r0, :FORHOST: as r1,:FORHOST: as r2 from :TBL: where :FILTER: and :PERIOD: group by :FORHOST: union select t2.fld1 as r1, t1.:FORHOST: as r2, t2.fld as r0 from :TBL: as t1, (select 2 as fld1, '0-8' as fld union select 3 as fld1, '8-12' as fld union select 4 as fld1, '12-18' as fld union select 5 as fld1, '18-24' as fld) as t2 where :FILTER: and :PERIOD: order by 2,1) as tt1 left join (select max(:CPUUSAGE:) as m2, :FORHOST: as m3, case when extract(hour from :DATEADD:) between 0 and 8 then '0-8' when extract(hour from :DATEADD:) between 9 and 12 then '8-12' when extract(hour from :DATEADD:) between 13 and 18 then '12-18' else '18-24' end as m4 from :TBL: where :FILTER: and :PERIOD: group by m3,m4) as tt2 on tt1.r1 = tt2.m3 and tt1.r2 = tt2.m4 order by tt1.r1, tt1.r0;

[Show Max Memory Usage in different time periods by site]
header=Site/Time period(hours)|Max Memory usage %;
ssql=select tt1.r2, IFNULL(tt2.m2, 0.0) from (select 1 as r0, :FORHOST: as r1,:FORHOST: as r2 from :TBL: where :FILTER: and :PERIOD: group by :FORHOST: union select t2.fld1 as r1, t1.:FORHOST: as r2, t2.fld as r0 from :TBL: as t1, (select 2 as fld1, '0-8' as fld union select 3 as fld1, '8-12' as fld union select 4 as fld1, '12-18' as fld union select 5 as fld1, '18-24' as fld) as t2 where :FILTER: and :PERIOD: order by 2,1) as tt1 left join (select max(:MEMUSAGEINPRCT:) as m2, :FORHOST: as m3, case when strftime("%H", :DATEADD:)+0 between 0 and 8 then '0-8' when strftime("%H", :DATEADD:)+0 between 9 and 12 then '8-12' when strftime("%H", :DATEADD:)+0 between 13 and 18 then '12-18' else '18-24' end as m4 from :TBL: where :FILTER: and :PERIOD: group by m3,m4) as tt2 on tt1.r1 = tt2.m3 and tt1.r2 = tt2.m4 order by tt1.r1, tt1.r0;
msql=select tt1.r2, IFNULL(tt2.m2, 0.0) from (select 1 as r0, :FORHOST: as r1,:FORHOST: as r2 from :TBL: where :FILTER: and :PERIOD: group by :FORHOST: union select t2.fld1 as r1, t1.:FORHOST: as r2, t2.fld as r0 from :TBL: as t1, (select 2 as fld1, '0-8' as fld union select 3 as fld1, '8-12' as fld union select 4 as fld1, '12-18' as fld union select 5 as fld1, '18-24' as fld) as t2 where :FILTER: and :PERIOD: order by 2,1) as tt1 left join (select max(:MEMUSAGEINPRCT:) as m2, :FORHOST: as m3, case when HOUR(:DATEADD:) between 0 and 8 then '0-8' when HOUR(:DATEADD:) between 9 and 12 then '8-12' when HOUR(:DATEADD:) between 13 and 18 then '12-18' else '18-24' end as m4 from :TBL: where :FILTER: and :PERIOD: group by m3,m4) as tt2 on tt1.r1 = tt2.m3 and tt1.r2 = tt2.m4 order by tt1.r1, tt1.r0;
psql=select tt1.r2, coalesce(tt2.m2, 0.0) from (select 1 as r0, :FORHOST: as r1,:FORHOST: as r2 from :TBL: where :FILTER: and :PERIOD: group by :FORHOST: union select t2.fld1 as r1, t1.:FORHOST: as r2, t2.fld as r0 from :TBL: as t1, (select 2 as fld1, '0-8' as fld union select 3 as fld1, '8-12' as fld union select 4 as fld1, '12-18' as fld union select 5 as fld1, '18-24' as fld) as t2 where :FILTER: and :PERIOD: order by 2,1) as tt1 left join (select max(:MEMUSAGEINPRCT:) as m2, :FORHOST: as m3, case when extract(hour from :DATEADD:) between 0 and 8 then '0-8' when extract(hour from :DATEADD:) between 9 and 12 then '8-12' when extract(hour from :DATEADD:) between 13 and 18 then '12-18' else '18-24' end as m4 from :TBL: where :FILTER: and :PERIOD: group by m3,m4) as tt2 on tt1.r1 = tt2.m3 and tt1.r2 = tt2.m4 order by tt1.r1, tt1.r0;

[Show Max IO Usage in different time periods by site]
header=Site/Time period(hours)|Max IO usage (KB/s);
ssql=select tt1.r2, IFNULL(tt2.m2, 0.0) from (select 1 as r0, :FORHOST: as r1,:FORHOST: as r2 from :TBL: where :FILTER: and :PERIOD: group by :FORHOST: union select t2.fld1 as r1, t1.:FORHOST: as r2, t2.fld as r0 from :TBL: as t1, (select 2 as fld1, '0-8' as fld union select 3 as fld1, '8-12' as fld union select 4 as fld1, '12-18' as fld union select 5 as fld1, '18-24' as fld) as t2 where :FILTER: and :PERIOD: order by 2,1) as tt1 left join (select max(:BYTESREAD:+:BYTESWRITE:) as m2, :FORHOST: as m3, case when strftime("%H", :DATEADD:)+0 between 0 and 8 then '0-8' when strftime("%H", :DATEADD:)+0 between 9 and 12 then '8-12' when strftime("%H", :DATEADD:)+0 between 13 and 18 then '12-18' else '18-24' end as m4 from :TBL: where :FILTER: and :PERIOD: group by m3,m4) as tt2 on tt1.r1 = tt2.m3 and tt1.r2 = tt2.m4 order by tt1.r1, tt1.r0;
msql=select tt1.r2, IFNULL(tt2.m2, 0.0) from (select 1 as r0, :FORHOST: as r1,:FORHOST: as r2 from :TBL: where :FILTER: and :PERIOD: group by :FORHOST: union select t2.fld1 as r1, t1.:FORHOST: as r2, t2.fld as r0 from :TBL: as t1, (select 2 as fld1, '0-8' as fld union select 3 as fld1, '8-12' as fld union select 4 as fld1, '12-18' as fld union select 5 as fld1, '18-24' as fld) as t2 where :FILTER: and :PERIOD: order by 2,1) as tt1 left join (select max(:BYTESREAD:+:BYTESWRITE:) as m2, :FORHOST: as m3, case when HOUR(:DATEADD:) between 0 and 8 then '0-8' when HOUR(:DATEADD:) between 9 and 12 then '8-12' when HOUR(:DATEADD:) between 13 and 18 then '12-18' else '18-24' end as m4 from :TBL: where :FILTER: and :PERIOD: group by m3,m4) as tt2 on tt1.r1 = tt2.m3 and tt1.r2 = tt2.m4 order by tt1.r1, tt1.r0;
psql=select tt1.r2, coalesce(tt2.m2, 0.0) from (select 1 as r0, :FORHOST: as r1,:FORHOST: as r2 from :TBL: where :FILTER: and :PERIOD: group by :FORHOST: union select t2.fld1 as r1, t1.:FORHOST: as r2, t2.fld as r0 from :TBL: as t1, (select 2 as fld1, '0-8' as fld union select 3 as fld1, '8-12' as fld union select 4 as fld1, '12-18' as fld union select 5 as fld1, '18-24' as fld) as t2 where :FILTER: and :PERIOD: order by 2,1) as tt1 left join (select max(:BYTESREAD:+:BYTESWRITE:) as m2, :FORHOST: as m3, case when extract(hour from :DATEADD:) between 0 and 8 then '0-8' when extract(hour from :DATEADD:) between 9 and 12 then '8-12' when extract(hour from :DATEADD:) between 13 and 18 then '12-18' else '18-24' end as m4 from :TBL: where :FILTER: and :PERIOD: group by m3,m4) as tt2 on tt1.r1 = tt2.m3 and tt1.r2 = tt2.m4 order by tt1.r1, tt1.r0;
